### ISSUE TITLE
Telerik Dependency

### ISSUE THREAD

**Issue by TopCat6** [DNNCommunity/DNN.Newsletter#28]
## Please summarize your question in one sentence
Are there plans to remove dependency on Telerik?

## Give a more extended description
Mitchell Sellers DNNTelerikIdentifier tool shows that this module (Dnn.Modules.Newsletters.dll) has a dependency on Telerik. Are there plans to remove that dependency?

**Comment by valadas** [comment]
Yes it is in the plans. Since this is open source, we cannot garantee a timeframe, but it's absolutely in the plans. Of course PRs are also welcome towards that goal.

**Comment by valadas** [comment]
I am reopening the issue as a reminder
