### ISSUE TITLE
Issue With Pulling Roles if not Admin

### ISSUE THREAD

**Issue by TMCentral** [DNNCommunity/DNN.Newsletter#5]
Just updated DNN site from v5 all the way through to v8.  Upgraded Newsletters module (v8.0) and have an issue in this Module: when a User (not an admin but has view rights on Module) looks up Roles to send to, nothing shows up.  If a host account does the same, all (filtered) Portal Roles show up.  This wasn't default before - is there a way to set to allow lookup of Roles?

**Comment by TMCentral** [comment]
Any idea / help on this one?

**Comment by david-poindexter** [comment]
@TMCentral that is a great question. I am not sure the answer, but if I am successful in getting this project to build locally, I'll dig in and see if I can find an answer for you.

**Comment by david-poindexter** [comment]
@TMCentral I took a closer look into this and it appears to be working as designed.  This is an **Admin** level module and thus is designed for use by **Administrators**.  That said, the roles available to any given user with view permissions on this module will be the roles by which they have permissions to see.  I'll go ahead and close this issue now, but feel free to re-open if you need any additional assistance.
