### ISSUE TITLE
Sending 99K, bulk message confirmation sent but no bulk report

### ISSUE THREAD

**Issue by gncube** [DNNCommunity/DNN.Newsletter#6]
What is the maximum number of emails the newsletter can send in a given instance.

Running the Newsletter module and sent newsletter to 99K users. Only 3K showing as processed on SendGrid. How can one see from DNN how many emails were sent.

**Comment by david-poindexter** [comment]
@gncube that is a great question.  I am not sure the answer, but if I am successful in getting this project to build locally, I'll dig in and see if I can find an answer for you.

**Comment by david-poindexter** [comment]
@gncube I was able to get the project to build locally and took some time to look into this for you.  There is nothing the module code, or the DNN API, that explicitly limits the number of emails that can be sent in one session.  Any limits would be imposed by the SMTP server being used.

I'll go ahead and close this issue, but feel free to re-open if you'd like to discuss it further.
